#!/usr/bin/env python3
import sys
import os

# Add the current directory to sys.path so we can import hncli
sys.path.insert(0, os.path.abspath(os.path.dirname(__file__)))

from hncli.cli import cli

if __name__ == "__main__":
    cli()
